# -*- coding: utf-8 -*-
"""Simple-Pipeline

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19p8splUsBwPhbC9WA_U0iHZwtVPBsF9g
"""

import numpy as np

# For modelling
from sklearn.pipeline import Pipeline
from sklearn.decomposition import PCA
from sklearn.impute import SimpleImputer
from sklearn.ensemble import RandomForestClassifier

# Getting some data
from sklearn import datasets
from sklearn.model_selection import train_test_split

# The whole pipeline
iris = datasets.load_iris()
X = iris.data
y = iris.target

# Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=27)

# Initialising the pipeline
my_pipeline = Pipeline(steps=[("impute", SimpleImputer(strategy="median")),
                              ("pca", PCA()),
                              ("rf_clf", RandomForestClassifier())])

# training the models 
my_pipeline.fit(X_train, y_train)

# Testing the accuracy
preds = my_pipeline.predict(X_test)

print(np.mean(preds == y_test)) # Accuracy











