# -*- coding: utf-8 -*-
"""super_functions.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UwQrNTj11VQvHwt0pcZ9-HpRLQUk--Pc

super( ) = function used to give acces to the methods of a parent class. Returns a temporary object of a parent of a parent class when used
"""

class Rectangle:
    def __init__(self, length, width):
      self.length = length
      self.width = width
      # Length and width are common to both square and cube
      # Therefore we define it in the parent class

class Square(Rectangle):
    def __init__(self, length, width):
      super().__init__(length, width)
      # To access the init function from the parent class, we use the super function

    def area(self):
      return self.length * self. width

class Cube(Rectangle):

  def __init__(self, length, width, height):
    super().__init__(length, width)
    self.height = height
    # We get the lendth and width from the parent class
    # We do not have a height, therefore we separately define it.

  def volume(self):
    return self.length * self. width  * self.height

square = Square(3, 3)
cube = Cube(3, 2, 3)

print(square.area())

print(cube.volume())

